### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by dexterhussain** [ardexa/abb-pro33-inverters#2]
We have 20 Trio and 30 Trio installed 17 total , we are making a daisy chain , in daisy chain when a connection is made , first 7 are working correctly, and 5 in same building are also  , when we connection two buildings , we start getting checksum error on the last inverter which is connecting to inverter in next building. Any Idea or help why is being caused?

**Comment by gxcora** [comment]
Not sure. but check whether you need a terminating resistor. Please see the user manual for the inverter.
